### PR TITLE
feat: add /speed page

### PR DESCRIPTION
**Pull request by mazipan**
Screen Shot 2021-02-18 at 18 13 39

@adibfirman You need to add `PSI_API_KEY` to your Secret on Github Action.

Also this is still using dummy report for testing purpose. You can delete the dummy report after you got your first report via cron job.

How to add new secret in Github Actions
https://docs.github.com/en/actions/reference/encrypted-secrets

How to create new API Key for PSI
https://developers.google.com/speed/docs/insights/v5/get-started

Read more on https://github.com/mazipan/psi-gh-action

### CODE REVIEW

**Comment by adibfirman** [comment]
woww, really appreciated mas, because its just a personal web and never over-thinking about performance, thank you very muchh @mazipan 🙏 

I will add the `PSI_API_KEY` and then looks how the best UI on the `/speed` will look like 😅😎

**Comment by mazipan** [comment]
Yes, I just create a basic UI for you. 
I don't want to create a fancy UI in the first place.
You can create a better UI by your hand.

**Comment by mazipan** [comment]
I suggest to merge the PR first, and let the cron job running.

After got some reports and understand the data, you can decide the best UI for your case.

Maybe you can take a look some of existing page on:

- https://mazipan.space/speed
- https://jefrydco.id/speed/

**Comment by mazipan** [comment]
Are you already add `PSI_API_KEY` on the https://github.com/adibfirman/adibfirman.github.io/settings/secrets/actions

**Comment by adibfirman** [comment]
@mazipan nah, on it 🔥

**Pull request merged**
