### PR TITLE
chore: increase the cronjob frequency

### PR DESCRIPTION
**Pull request by mazipan**

### CODE REVIEW

**Comment by mazipan** [comment]
There is anomaly in the Action `https://github.com/adibfirman/adibfirman.github.io/runs/1984441286?check_suite_focus=true`, it still read the `branch` as `master` not `main`.

That's why the report didn't pushed correctly.

**Comment by adibfirman** [comment]
ya on the prev PR the config was setup in the master branch 😅... ok i guess in this PR change the target branch right?

**Comment by mazipan** [comment]
Also increase the frequency to get more updates score @adibfirman

**Comment by adibfirman** [comment]
I see, noted thanks mas @mazipan

**Pull request merged**
